Repository OCA/fleet, pull requests merged in 2020-06, with the labels that each got.

#7 [12][ADD] new module fleet_vehicle_category
  fleet_vehicle_category/README.rst
  fleet_vehicle_category/__init__.py
  fleet_vehicle_category/__manifest__.py
  fleet_vehicle_category/models/__init__.py
  fleet_vehicle_category/models/fleet_vehicle.py
  fleet_vehicle_category/models/fleet_vehicle_category.py
  fleet_vehicle_category/readme/CONTRIBUTORS.rst
  fleet_vehicle_category/readme/DESCRIPTION.rst
  fleet_vehicle_category/readme/HISTORY.rst
  fleet_vehicle_category/security/ir.model.access.csv
  fleet_vehicle_category/static/description/icon.png
  fleet_vehicle_category/static/description/index.html
  fleet_vehicle_category/views/fleet_vehicle_views.xml
Labels: approved, bot is merging ⏳

#8 [13.0] [MIG] fleet vehicle category
  fleet_vehicle_category/README.rst
  fleet_vehicle_category/__init__.py
  fleet_vehicle_category/__manifest__.py
  fleet_vehicle_category/models/__init__.py
  fleet_vehicle_category/models/fleet_vehicle.py
  fleet_vehicle_category/models/fleet_vehicle_category.py
  fleet_vehicle_category/readme/CONTRIBUTORS.rst
  fleet_vehicle_category/readme/DESCRIPTION.rst
  fleet_vehicle_category/readme/HISTORY.rst
  fleet_vehicle_category/security/ir.model.access.csv
  fleet_vehicle_category/static/description/icon.png
  fleet_vehicle_category/static/description/index.html
  fleet_vehicle_category/views/fleet_vehicle_views.xml
Labels: bot is merging ⏳

#1 [13.0][ADD] fleet_vehicle_history_date_end: Assign end date in vehicle's drivers history
  fleet_vehicle_history_date_end/__init__.py
  fleet_vehicle_history_date_end/__manifest__.py
  fleet_vehicle_history_date_end/models/__init__.py
  fleet_vehicle_history_date_end/models/fleet_vehicle_assignation_log.py
  fleet_vehicle_history_date_end/readme/CONTRIBUTORS.rst
  fleet_vehicle_history_date_end/readme/DESCRIPTION.rst
  fleet_vehicle_history_date_end/tests/__init__.py
  fleet_vehicle_history_date_end/tests/test_vehicle_history_date_end.py
  setup/fleet_vehicle_history_date_end/odoo/addons/fleet_vehicle_history_date_end
  setup/fleet_vehicle_history_date_end/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#3 [13.0][ADD] fleet_vehicle_service_kanban: Kanban features in vehicle services.
  fleet_vehicle_service_kanban/__init__.py
  fleet_vehicle_service_kanban/__manifest__.py
  fleet_vehicle_service_kanban/data/fleet_vehicle_log_services_stage_data.xml
  fleet_vehicle_service_kanban/data/mail_message_subtype_data.xml
  fleet_vehicle_service_kanban/models/__init__.py
  fleet_vehicle_service_kanban/models/fleet_vehicle_log_services.py
  fleet_vehicle_service_kanban/models/fleet_vehicle_log_services_stage.py
  fleet_vehicle_service_kanban/models/fleet_vehicle_log_services_tag.py
  fleet_vehicle_service_kanban/readme/CONTRIBUTORS.rst
  fleet_vehicle_service_kanban/readme/DESCRIPTION.rst
  fleet_vehicle_service_kanban/security/ir.model.access.csv
  fleet_vehicle_service_kanban/tests/__init__.py
  fleet_vehicle_service_kanban/tests/common.py
  fleet_vehicle_service_kanban/tests/test_vehicle_log_services.py
  fleet_vehicle_service_kanban/views/fleet_service_type_views.xml
  fleet_vehicle_service_kanban/views/fleet_vehicle_log_services_stage_views.xml
  fleet_vehicle_service_kanban/views/fleet_vehicle_log_services_tag_views.xml
  fleet_vehicle_service_kanban/views/fleet_vehicle_log_services_views.xml
  fleet_vehicle_service_kanban/views/mail_activity_type_views.xml
  setup/fleet_vehicle_service_kanban/odoo/addons/fleet_vehicle_service_kanban
  setup/fleet_vehicle_service_kanban/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#2 [13.0][ADD] fleet_vehicle_license_plate_alt: Alternative license plate for vehicles
  fleet_vehicle_license_plate_alt/__init__.py
  fleet_vehicle_license_plate_alt/__manifest__.py
  fleet_vehicle_license_plate_alt/models/__init__.py
  fleet_vehicle_license_plate_alt/models/fleet_vehicle.py
  fleet_vehicle_license_plate_alt/readme/CONTRIBUTORS.rst
  fleet_vehicle_license_plate_alt/readme/DESCRIPTION.rst
  fleet_vehicle_license_plate_alt/tests/__init__.py
  fleet_vehicle_license_plate_alt/tests/test_vehicle_license_plate_alt.py
  fleet_vehicle_license_plate_alt/views/fleet_vehicle_views.xml
  setup/fleet_vehicle_license_plate_alt/odoo/addons/fleet_vehicle_license_plate_alt
  setup/fleet_vehicle_license_plate_alt/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#4 [13.0][ADD] fleet_vehicle_service_calendar: Scheduling meetings for vehicle services
  fleet_vehicle_service_calendar/__init__.py
  fleet_vehicle_service_calendar/__manifest__.py
  fleet_vehicle_service_calendar/models/__init__.py
  fleet_vehicle_service_calendar/models/calendar_event.py
  fleet_vehicle_service_calendar/models/fleet_vehicle_log_services.py
  fleet_vehicle_service_calendar/readme/CONTRIBUTORS.rst
  fleet_vehicle_service_calendar/readme/DESCRIPTION.rst
  fleet_vehicle_service_calendar/tests/__init__.py
  fleet_vehicle_service_calendar/tests/test_vehicle_service_calendar.py
  fleet_vehicle_service_calendar/views/calendar_event_views.xml
  fleet_vehicle_service_calendar/views/fleet_vehicle_log_services_views.xml
  setup/fleet_vehicle_service_calendar/odoo/addons/fleet_vehicle_service_calendar
  setup/fleet_vehicle_service_calendar/setup.py
Labels: approved, bot is merging ⏳, needs review

#9 [MIG] 12.0 mig fleet vehicle license plate alt
  fleet_vehicle_license_plate_alt/README.rst
  fleet_vehicle_license_plate_alt/__init__.py
  fleet_vehicle_license_plate_alt/__manifest__.py
  fleet_vehicle_license_plate_alt/models/__init__.py
  fleet_vehicle_license_plate_alt/models/fleet_vehicle.py
  fleet_vehicle_license_plate_alt/readme/CONTRIBUTORS.rst
  fleet_vehicle_license_plate_alt/readme/DESCRIPTION.rst
  fleet_vehicle_license_plate_alt/static/description/icon.png
  fleet_vehicle_license_plate_alt/static/description/index.html
  fleet_vehicle_license_plate_alt/tests/__init__.py
  fleet_vehicle_license_plate_alt/tests/test_vehicle_license_plate_alt.py
  fleet_vehicle_license_plate_alt/views/fleet_vehicle_views.xml
Labels: approved, bot is merging ⏳

#10 [MIG][12.0] fleet vehicle history date end
  fleet_vehicle_history_date_end/README.rst
  fleet_vehicle_history_date_end/__init__.py
  fleet_vehicle_history_date_end/__manifest__.py
  fleet_vehicle_history_date_end/models/__init__.py
  fleet_vehicle_history_date_end/models/fleet_vehicle_assignation_log.py
  fleet_vehicle_history_date_end/readme/CONTRIBUTORS.rst
  fleet_vehicle_history_date_end/readme/DESCRIPTION.rst
  fleet_vehicle_history_date_end/static/description/icon.png
  fleet_vehicle_history_date_end/static/description/index.html
  fleet_vehicle_history_date_end/tests/__init__.py
  fleet_vehicle_history_date_end/tests/test_vehicle_history_date_end.py
Labels: bot is merging ⏳

#12 [MIG][12.0] fleet vehicle service kanban: Backport 13.0 to 12.0
  fleet_vehicle_service_kanban/README.rst
  fleet_vehicle_service_kanban/__init__.py
  fleet_vehicle_service_kanban/__manifest__.py
  fleet_vehicle_service_kanban/data/fleet_vehicle_log_services_stage_data.xml
  fleet_vehicle_service_kanban/data/mail_message_subtype_data.xml
  fleet_vehicle_service_kanban/models/__init__.py
  fleet_vehicle_service_kanban/models/fleet_vehicle_log_services.py
  fleet_vehicle_service_kanban/models/fleet_vehicle_log_services_stage.py
  fleet_vehicle_service_kanban/models/fleet_vehicle_log_services_tag.py
  fleet_vehicle_service_kanban/readme/CONTRIBUTORS.rst
  fleet_vehicle_service_kanban/readme/DESCRIPTION.rst
  fleet_vehicle_service_kanban/security/ir.model.access.csv
  fleet_vehicle_service_kanban/static/description/icon.png
  fleet_vehicle_service_kanban/static/description/index.html
  fleet_vehicle_service_kanban/tests/__init__.py
  fleet_vehicle_service_kanban/tests/common.py
  fleet_vehicle_service_kanban/tests/test_vehicle_log_services.py
  fleet_vehicle_service_kanban/views/fleet_service_type_views.xml
  fleet_vehicle_service_kanban/views/fleet_vehicle_log_services_stage_views.xml
  fleet_vehicle_service_kanban/views/fleet_vehicle_log_services_tag_views.xml
  fleet_vehicle_service_kanban/views/fleet_vehicle_log_services_views.xml
  fleet_vehicle_service_kanban/views/mail_activity_type_views.xml
Labels: approved, bot is merging ⏳

#13 [FIX] fleet_vehicle_history_date_end: Remove test that checks the dat…
  fleet_vehicle_history_date_end/tests/test_vehicle_history_date_end.py
Labels: bot is merging ⏳

#11 [MIG][12.0] fleet vehicle service calendar: Backporting 13.0 to 12.0
  fleet_vehicle_service_calendar/README.rst
  fleet_vehicle_service_calendar/__init__.py
  fleet_vehicle_service_calendar/__manifest__.py
  fleet_vehicle_service_calendar/models/__init__.py
  fleet_vehicle_service_calendar/models/calendar_event.py
  fleet_vehicle_service_calendar/models/fleet_vehicle_log_services.py
  fleet_vehicle_service_calendar/readme/CONTRIBUTORS.rst
  fleet_vehicle_service_calendar/readme/DESCRIPTION.rst
  fleet_vehicle_service_calendar/static/description/icon.png
  fleet_vehicle_service_calendar/static/description/index.html
  fleet_vehicle_service_calendar/tests/__init__.py
  fleet_vehicle_service_calendar/tests/test_vehicle_service_calendar.py
  fleet_vehicle_service_calendar/views/calendar_event_views.xml
  fleet_vehicle_service_calendar/views/fleet_vehicle_log_services_views.xml
Labels: approved, bot is merging ⏳

#14 [FIX] toggle active service button
  fleet_vehicle_service_kanban/views/fleet_vehicle_log_services_views.xml
Labels: approved, bot is merging ⏳
