Repository OCA/fleet, pull requests merged in 2023-07, with the labels that each got.

#117 [16.0][MIG] fleet_vehicle_configuration: Migration to 16.0
  fleet_vehicle_configuration/README.rst
  fleet_vehicle_configuration/__init__.py
  fleet_vehicle_configuration/__manifest__.py
  fleet_vehicle_configuration/i18n/fleet_vehicle_configuration.pot
  fleet_vehicle_configuration/i18n/it.po
  fleet_vehicle_configuration/models/__init__.py
  fleet_vehicle_configuration/models/fleet_configuration.py
  fleet_vehicle_configuration/models/fleet_vehicle.py
  fleet_vehicle_configuration/readme/CONTRIBUTORS.rst
  fleet_vehicle_configuration/readme/DESCRIPTION.rst
  fleet_vehicle_configuration/security/ir.model.access.csv
  fleet_vehicle_configuration/static/description/icon.png
  fleet_vehicle_configuration/static/description/index.html
  fleet_vehicle_configuration/views/fleet_vehicle.xml
  fleet_vehicle_configuration/views/fleet_vehicle_configuration.xml
  setup/fleet_vehicle_configuration/odoo/addons/fleet_vehicle_configuration
  setup/fleet_vehicle_configuration/setup.py
Labels: bot is merging ⏳

#101 [15.0] [MIG] fleet_vehicle_service_calendar: Migration to 15.0
  fleet_vehicle_service_calendar/README.rst
  fleet_vehicle_service_calendar/__init__.py
  fleet_vehicle_service_calendar/__manifest__.py
  fleet_vehicle_service_calendar/i18n/fleet_vehicle_service_calendar.pot
  fleet_vehicle_service_calendar/models/__init__.py
  fleet_vehicle_service_calendar/models/calendar_event.py
  fleet_vehicle_service_calendar/models/fleet_vehicle_log_services.py
  fleet_vehicle_service_calendar/readme/CONTRIBUTORS.rst
  fleet_vehicle_service_calendar/readme/DESCRIPTION.rst
  fleet_vehicle_service_calendar/static/description/icon.png
  fleet_vehicle_service_calendar/static/description/index.html
  fleet_vehicle_service_calendar/tests/__init__.py
  fleet_vehicle_service_calendar/tests/test_calendar_event.py
  fleet_vehicle_service_calendar/tests/test_vehicle_service_calendar.py
  fleet_vehicle_service_calendar/views/calendar_event_views.xml
  fleet_vehicle_service_calendar/views/fleet_vehicle_log_services_views.xml
  setup/fleet_vehicle_service_calendar/odoo/addons/fleet_vehicle_service_calendar
  setup/fleet_vehicle_service_calendar/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#116 [14.0][FIX] fleet_vehicle_services_kanban: remove duplicate tags from view fleet_vehicle_log_services_view_form
  fleet_vehicle_service_kanban/views/fleet_vehicle_log_services_views.xml
Labels: bot is merging ⏳

#119 [15.0][MIG] fleet_vehicle_category: Migration to 15.0
  fleet_vehicle_category/README.rst
  fleet_vehicle_category/__init__.py
  fleet_vehicle_category/__manifest__.py
  fleet_vehicle_category/i18n/fleet_vehicle_category.pot
  fleet_vehicle_category/i18n/it.po
  fleet_vehicle_category/i18n/pt_BR.po
  fleet_vehicle_category/i18n/tr.po
  fleet_vehicle_category/models/__init__.py
  fleet_vehicle_category/models/fleet_vehicle.py
  fleet_vehicle_category/models/fleet_vehicle_category.py
  fleet_vehicle_category/readme/CONTRIBUTORS.rst
  fleet_vehicle_category/readme/DESCRIPTION.rst
  fleet_vehicle_category/readme/HISTORY.rst
  fleet_vehicle_category/security/ir.model.access.csv
  fleet_vehicle_category/static/description/icon.png
  fleet_vehicle_category/static/description/index.html
  fleet_vehicle_category/views/fleet_vehicle_views.xml
  setup/fleet_vehicle_category/odoo/addons/fleet_vehicle_category
  setup/fleet_vehicle_category/setup.py
Labels: approved, bot is merging ⏳

#118 [15.0][MIG] fleet_vehicle_history_date_end: Migration to 15.0
  fleet_vehicle_history_date_end/README.rst
  fleet_vehicle_history_date_end/__init__.py
  fleet_vehicle_history_date_end/__manifest__.py
  fleet_vehicle_history_date_end/i18n/fleet_vehicle_history_date_end.pot
  fleet_vehicle_history_date_end/i18n/it.po
  fleet_vehicle_history_date_end/i18n/pt_BR.po
  fleet_vehicle_history_date_end/models/__init__.py
  fleet_vehicle_history_date_end/models/fleet_vehicle_assignation_log.py
  fleet_vehicle_history_date_end/readme/CONTRIBUTORS.rst
  fleet_vehicle_history_date_end/readme/DESCRIPTION.rst
  fleet_vehicle_history_date_end/static/description/icon.png
  fleet_vehicle_history_date_end/static/description/index.html
  fleet_vehicle_history_date_end/tests/__init__.py
  fleet_vehicle_history_date_end/tests/test_vehicle_history_date_end.py
  setup/fleet_vehicle_history_date_end/odoo/addons/fleet_vehicle_history_date_end
  setup/fleet_vehicle_history_date_end/setup.py
Labels: approved, bot is merging ⏳
