Repository OCA/fleet, pull requests merged in 2025-04, with the labels that each got.

#181 [18.0][MIG] fleet_vehicle_inspection: Migration to 18.0
  fleet_vehicle_inspection/README.rst
  fleet_vehicle_inspection/__init__.py
  fleet_vehicle_inspection/__manifest__.py
  fleet_vehicle_inspection/data/fleet_vehicle_inspection.xml
  fleet_vehicle_inspection/demo/fleet_vehicle_inspection.xml
  fleet_vehicle_inspection/i18n/es.po
  fleet_vehicle_inspection/i18n/fleet_vehicle_inspection.pot
  fleet_vehicle_inspection/i18n/it.po
  fleet_vehicle_inspection/i18n/pt_BR.po
  fleet_vehicle_inspection/models/__init__.py
  fleet_vehicle_inspection/models/fleet_vehicle.py
  fleet_vehicle_inspection/models/fleet_vehicle_inspection.py
  fleet_vehicle_inspection/models/fleet_vehicle_inspection_item.py
  fleet_vehicle_inspection/models/fleet_vehicle_inspection_line.py
  fleet_vehicle_inspection/models/fleet_vehicle_inspection_line_image.py
  fleet_vehicle_inspection/pyproject.toml
  fleet_vehicle_inspection/readme/CONFIGURE.md
  fleet_vehicle_inspection/readme/CONTRIBUTORS.md
  fleet_vehicle_inspection/readme/CREDITS.md
  fleet_vehicle_inspection/readme/DESCRIPTION.md
  fleet_vehicle_inspection/readme/ROADMAP.md
  fleet_vehicle_inspection/security/ir.model.access.csv
  fleet_vehicle_inspection/security/security.xml
  fleet_vehicle_inspection/static/description/banner.png
  fleet_vehicle_inspection/static/description/icon.png
  fleet_vehicle_inspection/static/description/index.html
  fleet_vehicle_inspection/tests/__init__.py
  fleet_vehicle_inspection/tests/test_fleet_vehicle_inspection.py
  fleet_vehicle_inspection/views/fleet_vehicle_inspection_item_views.xml
  fleet_vehicle_inspection/views/fleet_vehicle_inspection_line_views.xml
  fleet_vehicle_inspection/views/fleet_vehicle_inspection_views.xml
  fleet_vehicle_inspection/views/fleet_vehicle_views.xml
Labels: approved, bot is merging ⏳

#175 [17.0][MIG] fleet_vehicle_history_date_end: Migration to 17.0
  fleet_vehicle_history_date_end/README.rst
  fleet_vehicle_history_date_end/__init__.py
  fleet_vehicle_history_date_end/__manifest__.py
  fleet_vehicle_history_date_end/i18n/fleet_vehicle_history_date_end.pot
  fleet_vehicle_history_date_end/i18n/it.po
  fleet_vehicle_history_date_end/i18n/pt_BR.po
  fleet_vehicle_history_date_end/models/__init__.py
  fleet_vehicle_history_date_end/models/fleet_vehicle_assignation_log.py
  fleet_vehicle_history_date_end/pyproject.toml
  fleet_vehicle_history_date_end/readme/CONTRIBUTORS.md
  fleet_vehicle_history_date_end/readme/DESCRIPTION.md
  fleet_vehicle_history_date_end/static/description/icon.png
  fleet_vehicle_history_date_end/static/description/index.html
  fleet_vehicle_history_date_end/tests/__init__.py
  fleet_vehicle_history_date_end/tests/test_vehicle_history_date_end.py
Labels: approved, ready to merge, bot is merging ⏳

#168 [18.0][MIG] fleet_vehicle_category: Migration to 18.0
  fleet_vehicle_category/README.rst
  fleet_vehicle_category/__init__.py
  fleet_vehicle_category/__manifest__.py
  fleet_vehicle_category/i18n/fleet_vehicle_category.pot
  fleet_vehicle_category/i18n/it.po
  fleet_vehicle_category/i18n/pt_BR.po
  fleet_vehicle_category/i18n/tr.po
  fleet_vehicle_category/models/__init__.py
  fleet_vehicle_category/models/fleet_vehicle.py
  fleet_vehicle_category/models/fleet_vehicle_category.py
  fleet_vehicle_category/pyproject.toml
  fleet_vehicle_category/readme/CONTRIBUTORS.md
  fleet_vehicle_category/readme/DESCRIPTION.md
  fleet_vehicle_category/readme/HISTORY.md
  fleet_vehicle_category/security/ir.model.access.csv
  fleet_vehicle_category/static/description/icon.png
  fleet_vehicle_category/static/description/index.html
  fleet_vehicle_category/views/fleet_vehicle_views.xml
Labels: approved, ready to merge, merged 🎉

#170 [18.0][MIG] fleet_vehicle_fuel_type_ethanol: Migration to 18.0
  fleet_vehicle_fuel_type_ethanol/README.rst
  fleet_vehicle_fuel_type_ethanol/__init__.py
  fleet_vehicle_fuel_type_ethanol/__manifest__.py
  fleet_vehicle_fuel_type_ethanol/i18n/es.po
  fleet_vehicle_fuel_type_ethanol/i18n/fleet_vehicle_fuel_type_ethanol.pot
  fleet_vehicle_fuel_type_ethanol/i18n/it.po
  fleet_vehicle_fuel_type_ethanol/i18n/pt_BR.po
  fleet_vehicle_fuel_type_ethanol/i18n/sv.po
  fleet_vehicle_fuel_type_ethanol/models/__init__.py
  fleet_vehicle_fuel_type_ethanol/models/fleet_vehicle.py
  fleet_vehicle_fuel_type_ethanol/pyproject.toml
  fleet_vehicle_fuel_type_ethanol/readme/CONTRIBUTORS.md
  fleet_vehicle_fuel_type_ethanol/readme/CREDITS.md
  fleet_vehicle_fuel_type_ethanol/readme/DESCRIPTION.md
  fleet_vehicle_fuel_type_ethanol/static/description/banner.png
  fleet_vehicle_fuel_type_ethanol/static/description/icon.png
  fleet_vehicle_fuel_type_ethanol/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#177 [18.0][MIG] fleet_vehicle_configuration: Migration to 18.0
  fleet_vehicle_configuration/README.rst
  fleet_vehicle_configuration/__init__.py
  fleet_vehicle_configuration/__manifest__.py
  fleet_vehicle_configuration/i18n/es.po
  fleet_vehicle_configuration/i18n/fleet_vehicle_configuration.pot
  fleet_vehicle_configuration/i18n/it.po
  fleet_vehicle_configuration/i18n/sv.po
  fleet_vehicle_configuration/models/__init__.py
  fleet_vehicle_configuration/models/fleet_configuration.py
  fleet_vehicle_configuration/models/fleet_vehicle.py
  fleet_vehicle_configuration/pyproject.toml
  fleet_vehicle_configuration/readme/CONTRIBUTORS.md
  fleet_vehicle_configuration/readme/DESCRIPTION.md
  fleet_vehicle_configuration/security/ir.model.access.csv
  fleet_vehicle_configuration/static/description/icon.png
  fleet_vehicle_configuration/static/description/index.html
  fleet_vehicle_configuration/views/fleet_vehicle.xml
  fleet_vehicle_configuration/views/fleet_vehicle_configuration.xml
Labels: approved, ready to merge, bot is merging ⏳

#174 [17.0][MIG] fleet_vehicle_fuel_capacity: Migration to 17.0
  fleet_vehicle_fuel_capacity/README.rst
  fleet_vehicle_fuel_capacity/__init__.py
  fleet_vehicle_fuel_capacity/__manifest__.py
  fleet_vehicle_fuel_capacity/i18n/es.po
  fleet_vehicle_fuel_capacity/i18n/fleet_vehicle_fuel_capacity.pot
  fleet_vehicle_fuel_capacity/i18n/it.po
  fleet_vehicle_fuel_capacity/i18n/pt_BR.po
  fleet_vehicle_fuel_capacity/i18n/sv.po
  fleet_vehicle_fuel_capacity/models/__init__.py
  fleet_vehicle_fuel_capacity/models/fleet_vehicle.py
  fleet_vehicle_fuel_capacity/pyproject.toml
  fleet_vehicle_fuel_capacity/readme/CONTRIBUTORS.md
  fleet_vehicle_fuel_capacity/readme/CREDITS.md
  fleet_vehicle_fuel_capacity/readme/DESCRIPTION.md
  fleet_vehicle_fuel_capacity/readme/ROADMAP.md
  fleet_vehicle_fuel_capacity/static/description/banner.png
  fleet_vehicle_fuel_capacity/static/description/icon.png
  fleet_vehicle_fuel_capacity/static/description/index.html
  fleet_vehicle_fuel_capacity/tests.zip
  fleet_vehicle_fuel_capacity/views/fleet_vehicle.xml
Labels: approved, ready to merge, bot is merging ⏳

#172 [18.0][MIG] fleet_vehicle_service_services: Migration to 18.0
  fleet_vehicle_service_services/README.rst
  fleet_vehicle_service_services/__init__.py
  fleet_vehicle_service_services/__manifest__.py
  fleet_vehicle_service_services/i18n/es.po
  fleet_vehicle_service_services/i18n/fleet_vehicle_service_services.pot
  fleet_vehicle_service_services/i18n/it.po
  fleet_vehicle_service_services/i18n/pt_BR.po
  fleet_vehicle_service_services/i18n/sv.po
  fleet_vehicle_service_services/models/__init__.py
  fleet_vehicle_service_services/models/fleet_vehicle_cost.py
  fleet_vehicle_service_services/pyproject.toml
  fleet_vehicle_service_services/readme/CONTRIBUTORS.md
  fleet_vehicle_service_services/readme/DESCRIPTION.md
  fleet_vehicle_service_services/static/description/icon.png
  fleet_vehicle_service_services/static/description/index.html
  fleet_vehicle_service_services/views/fleet_vehicle_cost_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#160 [16.0][IMP] fleet_vehicle_inspection_template: add sequence to inspection template
  fleet_vehicle_inspection_template/models/fleet_vehicle_inspection.py
  fleet_vehicle_inspection_template/models/fleet_vehicle_inspection_template_line.py
  fleet_vehicle_inspection_template/tests/test_fleet_vehicle_inspection_template.py
  fleet_vehicle_inspection_template/views/fleet_vehicle_inspection_template.xml
Labels: approved, ready to merge, bot is merging ⏳
